/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepoImport } from './routes/$repo'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RepoRoute = RepoImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$repo': {
      id: '/$repo'
      path: '/$repo'
      fullPath: '/$repo'
      preLoaderRoute: typeof RepoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$repo': typeof RepoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$repo': typeof RepoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$repo': typeof RepoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$repo'
  id: '__root__' | '/' | '/$repo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRoute: typeof RepoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRoute: RepoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$repo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$repo": {
      "filePath": "$repo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
